
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ATC_Approve
{

    public int ApproveID { get; set; }

    public string ApproveCode { get; set; }

    public string InternalNo { get; set; }

    public string ApproveTitle { get; set; }

    public Nullable<int> ApproveOrder { get; set; }

    public string DocumentCode { get; set; }

    public string BillCode { get; set; }

    public System.Guid CreateUserID { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.Guid ApprovalUserID { get; set; }

    public Nullable<System.DateTime> ApprovalDate { get; set; }

    public bool IsApprovaled { get; set; }

    public Nullable<bool> IsPass { get; set; }

    public bool IsWhole { get; set; }

    public string ApprovalContent { get; set; }

    public string ApprovalSuggestion { get; set; }

    public string ApprovalResult { get; set; }

    public string ApprovalRemark { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

}

}
