
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ATC_User
{

    public System.Guid UserID { get; set; }

    public string UserCode { get; set; }

    public string UserName { get; set; }

    public string UserSpell { get; set; }

    public string UserPassword { get; set; }

    public Nullable<int> UserStatus { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string UserRemark { get; set; }

    public Nullable<bool> UseInternalProductPrice { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

}

}
