
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class BUS_ReviewBack
{

    public int BackID { get; set; }

    public Nullable<int> BillID { get; set; }

    public string Code { get; set; }

    public string Cause { get; set; }

    public string Result { get; set; }

    public string SubUserName { get; set; }

    public Nullable<System.DateTime> SubDate { get; set; }

    public string AppStatus { get; set; }

    public string Remark { get; set; }

}

}
