
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    public string CategoryCode { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDescription { get; set; }

    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public string ItemSpell { get; set; }

    public Nullable<int> ParentItemID { get; set; }

    public string ItemDescription { get; set; }

    public Nullable<bool> IsSystemItem { get; set; }

    public Nullable<int> StatusSort { get; set; }

    public Nullable<bool> IsEffective { get; set; }

    public string ItemRemark { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

}

}
