
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Dealer
{

    public int DealerID { get; set; }

    public string DealerCode { get; set; }

    public string DealerName { get; set; }

    public string DealerSpell { get; set; }

    public string DealerArea { get; set; }

    public string DealerProvince { get; set; }

    public string DealerCity { get; set; }

    public string DealerCounty { get; set; }

    public string DealerAddress { get; set; }

    public string DealerPhone { get; set; }

    public string DealerPostalCode { get; set; }

    public string DealerFaxNo { get; set; }

    public string DealerMail { get; set; }

    public string DealerWebSiteUrl { get; set; }

    public string BusinessPerson { get; set; }

    public string BusinessPersonSpell { get; set; }

    public string BusinessPhone { get; set; }

    public string DealerLeader { get; set; }

    public string LeaderSpell { get; set; }

    public string LeaderPhone { get; set; }

    public string LegalPerson { get; set; }

    public string LegalSpell { get; set; }

    public string LegalPhone { get; set; }

    public string OrganizationCode { get; set; }

    public string RegisterAddress { get; set; }

    public Nullable<System.DateTime> RegisterData { get; set; }

    public string RegisterCapital { get; set; }

    public string RegisterLicenseNo { get; set; }

    public Nullable<System.DateTime> LicenseValidateDate { get; set; }

    public string RegisterTaxNo { get; set; }

    public Nullable<System.DateTime> TaxValidateDate { get; set; }

    public string AccountBankName { get; set; }

    public string AccountNo { get; set; }

    public string AccountBankCode { get; set; }

    public string BusinessRange { get; set; }

    public string IndustryStyle { get; set; }

    public string DealerLevel { get; set; }

    public string DealerStyle { get; set; }

    public string DealerType { get; set; }

    public string EmployeeNum { get; set; }

    public Nullable<int> ParentDealerID { get; set; }

    public Nullable<int> EnterpriseID { get; set; }

    public Nullable<int> BusinessStatus { get; set; }

    public string DealerStatus { get; set; }

    public Nullable<int> PurchasePriceListID { get; set; }

    public Nullable<int> SalePriceListID { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string DealerRemark { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

    public string Reservation6 { get; set; }

    public string Reservation7 { get; set; }

    public string Reservation8 { get; set; }

    public string Reservation9 { get; set; }

    public string Reservation10 { get; set; }

}

}
