
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryStatistic
{

    public int InventoryStatisticID { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime EndDate { get; set; }

    public Nullable<int> WarehouseID { get; set; }

    public Nullable<int> StatusID { get; set; }

    public string StatusName { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string InventoryStatisticCode { get; set; }

}

}
