
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryDemolition
{

    public int DemolitionID { get; set; }

    public int StoreBillDetailID { get; set; }

    public Nullable<int> EntireCargoAmount { get; set; }

    public string EntireCargoStructureCode { get; set; }

    public Nullable<int> EntireCargoStructureID { get; set; }

    public string EntireCargoStructureName { get; set; }

    public Nullable<int> ScatteredCargoAmount { get; set; }

    public string ScatteredCargoStructureCode { get; set; }

    public Nullable<int> ScatteredCargoStructureID { get; set; }

    public string ScatteredCargoStructureName { get; set; }

}

}
