
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LabelTask
{

    public int TaskId { get; set; }

    public int LabelID { get; set; }

    public string LabelCode { get; set; }

    public int LabelType { get; set; }

    public int LabelComPort { get; set; }

    public string LabelAddress { get; set; }

    public string LightCode { get; set; }

    public Nullable<int> LabelStatus { get; set; }

    public string LabelContent { get; set; }

    public string StockOutNo { get; set; }

    public string MedicineCode { get; set; }

    public string BatchNo { get; set; }

    public Nullable<int> StockOutAmount { get; set; }

    public Nullable<int> StructureID { get; set; }

    public Nullable<int> StructureCode { get; set; }

    public string StructureLocation { get; set; }

    public Nullable<int> Amount { get; set; }

    public string StructureType { get; set; }

    public Nullable<int> TaskStatus { get; set; }

    public Nullable<int> LightComPort { get; set; }

    public string LightAddress { get; set; }

    public int BillDetailID { get; set; }

    public System.Guid WMSDetailID { get; set; }

}

}
