
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PDATask
{

    public int PDATaskID { get; set; }

    public int StoreID { get; set; }

    public int ProductID { get; set; }

    public string BatchNo { get; set; }

    public Nullable<System.DateTime> ProduceDate { get; set; }

    public Nullable<System.DateTime> ValidateDate { get; set; }

    public Nullable<int> BillAmount { get; set; }

    public Nullable<int> Amount { get; set; }

    public Nullable<int> StoreAmount { get; set; }

    public Nullable<int> TaskStatusID { get; set; }

    public string TaskStatus { get; set; }

    public int BillDetailID { get; set; }

    public System.Guid WMSDetailID { get; set; }

    public int StructureID { get; set; }

    public string StructureCode { get; set; }

    public string ProductName { get; set; }

    public string ProductSpec { get; set; }

}

}
