
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public int ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string ProductSpell { get; set; }

    public string CommonName { get; set; }

    public string TradeName { get; set; }

    public string EnglishName { get; set; }

    public string ChinesePinyin { get; set; }

    public string ProductBarCode { get; set; }

    public string ProductSpec { get; set; }

    public string ProductUnit { get; set; }

    public string PackageSpec { get; set; }

    public Nullable<int> PhysicTypeID { get; set; }

    public string PhysicType { get; set; }

    public Nullable<int> ProductStyleID { get; set; }

    public string ProductStyle { get; set; }

    public string AuthorizedNo { get; set; }

    public string ProducerName { get; set; }

    public string ProducerSpell { get; set; }

    public string ProductionAddress { get; set; }

    public string ProductionPostalCode { get; set; }

    public string ProductionPhone { get; set; }

    public string ProductionFaxNo { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonSpell { get; set; }

    public string ContactPhone { get; set; }

    public Nullable<bool> IsSupervise { get; set; }

    public string SuperviseSignBar { get; set; }

    public Nullable<int> StockMinAmount { get; set; }

    public Nullable<int> BatchPreWarningDays { get; set; }

    public string AcceptAgingTime { get; set; }

    public string TreatmentFor { get; set; }

    public string UsageDosage { get; set; }

    public string AdverseReaction { get; set; }

    public string Contraindication { get; set; }

    public string MatterAttention { get; set; }

    public string StockCondition { get; set; }

    public Nullable<bool> IsUseToPregnant { get; set; }

    public Nullable<bool> IsUseToChildren { get; set; }

    public Nullable<bool> IsUseToOldPeople { get; set; }

    public string Ingredient { get; set; }

    public string Character { get; set; }

    public string DrugInteraction { get; set; }

    public string Overdose { get; set; }

    public string ClinicalTrial { get; set; }

    public string Pharmacology { get; set; }

    public string Pharmacokinetics { get; set; }

    public string PerformanceStandard { get; set; }

    public string RegisterNo { get; set; }

    public string InstructionContent { get; set; }

    public Nullable<System.DateTime> InstructionDate { get; set; }

    public string PackagingProportion { get; set; }

    public Nullable<int> EntireCargoSpaceMaximum { get; set; }

    public Nullable<int> ScatteredCargoSpaceMaximum { get; set; }

    public Nullable<int> ScatteredCargoSpaceMinimum { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string ProductRemrk { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

    public string Reservation6 { get; set; }

    public string Reservation7 { get; set; }

    public string Reservation8 { get; set; }

    public string Reservation9 { get; set; }

    public string Reservation10 { get; set; }

    public Nullable<int> BusinessStatus { get; set; }

    public string ValidateYears { get; set; }

    public string FirstDealerName { get; set; }

    public string ProductStatus { get; set; }

    public string CycleType { get; set; }

    public Nullable<bool> IsForeignDrug { get; set; }

    public string ProductionOriginAddress { get; set; }

    public int DSpecialNum { get; set; }

    public int MSpecialNum { get; set; }

    public Nullable<int> PurchaseTaxID { get; set; }

    public string PurchaseTax { get; set; }

    public Nullable<int> SaleTaxID { get; set; }

    public string SaleTax { get; set; }

}

}
