
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Review
{

    public int ReviewID { get; set; }

    public string ReviewCode { get; set; }

    public Nullable<System.DateTime> ReviewDate { get; set; }

    public string ReviewPerson { get; set; }

    public string ReviewPersonSpell { get; set; }

    public Nullable<int> StatusID { get; set; }

    public string StatusName { get; set; }

    public string StatusSpell { get; set; }

    public Nullable<int> SaleBillID { get; set; }

    public string SaleBillCode { get; set; }

    public Nullable<int> StoreOutID { get; set; }

    public string StoreOutCode { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string ReviewRemark { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

    public string Reservation6 { get; set; }

    public string Reservation7 { get; set; }

    public string Reservation8 { get; set; }

    public string Reservation9 { get; set; }

    public string Reservation10 { get; set; }

}

}
