
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class StoreOutErrorLog
{

    public long StoreOutErrorLogId { get; set; }

    public Nullable<int> StoreID { get; set; }

    public string StoreCode { get; set; }

    public Nullable<int> DetailID { get; set; }

    public Nullable<int> ProductID { get; set; }

    public string ProductName { get; set; }

    public string BatchNumber { get; set; }

    public string PackageSpec { get; set; }

    public Nullable<System.DateTime> ProduceDate { get; set; }

    public Nullable<System.DateTime> ValidateDate { get; set; }

    public Nullable<int> Amount { get; set; }

    public Nullable<int> WarehouseID { get; set; }

    public string WarehouseName { get; set; }

    public Nullable<int> StructureID { get; set; }

    public string StructureCode { get; set; }

    public string StructureName { get; set; }

    public Nullable<int> StoreAmount { get; set; }

    public string Reason { get; set; }

}

}
