
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class StoreOutHistory
{

    public int StoreOutHistoryID { get; set; }

    public string StoreCode { get; set; }

    public int StructureID { get; set; }

    public int ProductID { get; set; }

    public string ProductBatchNumber { get; set; }

    public Nullable<System.DateTime> ProductionDate { get; set; }

    public Nullable<System.DateTime> ProductValidDate { get; set; }

    public int ProductAmount { get; set; }

    public string Manufacturer { get; set; }

    public string DosageForm { get; set; }

    public string PackagingSpecification { get; set; }

    public Nullable<System.DateTime> StoreOutDate { get; set; }

}

}
