
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class StoreOutReviewIdentity
{

    public int ReviewIdentityID { get; set; }

    public string ReviewIdentityCode { get; set; }

    public int StoreID { get; set; }

    public string StoreCode { get; set; }

    public string PDAIdentity { get; set; }

    public string OperationUsername { get; set; }

    public string OperationRealname { get; set; }

    public System.DateTime RelatedDate { get; set; }

    public bool IsReviewed { get; set; }

    public string ReviewCode { get; set; }

    public Nullable<System.DateTime> ReviewDate { get; set; }

    public string ReviewPerson { get; set; }

}

}
