
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class StoreBillDetail
{

    public int DetailID { get; set; }

    public int StoreID { get; set; }

    public int ProductID { get; set; }

    public string BatchNo { get; set; }

    public Nullable<System.DateTime> ProduceDate { get; set; }

    public Nullable<System.DateTime> ValidateDate { get; set; }

    public Nullable<int> BillAmount { get; set; }

    public Nullable<int> QualifiedAmount { get; set; }

    public Nullable<int> Amount { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string DetailRemark { get; set; }

    public string StatusID { get; set; }

    public string StatusName { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

    public string Reservation6 { get; set; }

    public string Reservation7 { get; set; }

    public string Reservation8 { get; set; }

    public string Reservation9 { get; set; }

    public string Reservation10 { get; set; }

    public Nullable<int> StoreAmount { get; set; }

    public string SterilizationBatchNo { get; set; }

    public Nullable<System.DateTime> SterilizationDate { get; set; }

    public string MakeBillStatus { get; set; }

    public string MakeCollectionsStatus { get; set; }

    public string MakeCollectionsCode { get; set; }

    public Nullable<System.DateTime> MakeCollectionsDate { get; set; }

}

}
