
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Warehouse
{

    public int WarehouseID { get; set; }

    public string WarehouseCode { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseSpell { get; set; }

    public string WarehousePurpose { get; set; }

    public string WarehouseType { get; set; }

    public string WarehousePhone { get; set; }

    public string PostalCode { get; set; }

    public string FaxNo { get; set; }

    public string IsAnotherPlace { get; set; }

    public string WarehouseAddress { get; set; }

    public string WarehouseLeader { get; set; }

    public string LeaderSpell { get; set; }

    public string LeaderPhone { get; set; }

    public string BusinessPerson { get; set; }

    public string BusinessPersonSpell { get; set; }

    public string BusinessPhone { get; set; }

    public string FloorSpace { get; set; }

    public string Volume { get; set; }

    public Nullable<int> EnterpriseID { get; set; }

    public Nullable<int> ParentWarehouseID { get; set; }

    public Nullable<System.Guid> CreateUserID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.Guid> LastModifyUserID { get; set; }

    public Nullable<System.DateTime> LastModifyDate { get; set; }

    public string WarehouseRemark { get; set; }

    public string Reservation1 { get; set; }

    public string Reservation2 { get; set; }

    public string Reservation3 { get; set; }

    public string Reservation4 { get; set; }

    public string Reservation5 { get; set; }

    public string Reservation6 { get; set; }

    public string Reservation7 { get; set; }

    public string Reservation8 { get; set; }

    public string Reservation9 { get; set; }

    public string Reservation10 { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
