
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class WMSScannedRegulatoryCode
{

    public int ScannedRegulatoryCodeID { get; set; }

    public int StoreID { get; set; }

    public string StoreCode { get; set; }

    public int ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductBarcode { get; set; }

    public string ScannedRegulatoryCode { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CreateUsername { get; set; }

}

}
