
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Model
{

using System;
    using System.Collections.Generic;
    
public partial class WMSUser
{

    public System.Guid UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Rolename { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreateDate { get; set; }

    public string Realname { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

}

}
